# Generated by Django 5.0.6 on 2024-05-23 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=100)),
                ('status', models.IntegerField(choices=[(1, 'Activo'), (2, 'Inactivo'), (3, 'Eliminado')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BachelorProgramInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('period', models.IntegerField(choices=[('2019 - 1', '2019 - 1'), ('2019 - 2', '2019 - 2'), ('2020 - 1', '2020 - 1'), ('2020 - 2', '2020 - 2'), ('2021 - 1', '2021 - 1'), ('2021 - 2', '2021 - 2'), ('2022 - 1', '2022 - 1'), ('2022 - 2', '2022 - 2'), ('2023 - 1', '2023 - 1'), ('2023 - 2', '2023 - 2')], null=True)),
                ('num_students_male', models.IntegerField(default=0)),
                ('num_students_female', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('td', models.IntegerField(choices=[(1, 'text'), (2, 'number')], null=True)),
                ('content', models.CharField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Indicator1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.IntegerField(choices=[('2019 - 1', '2019 - 1'), ('2019 - 2', '2019 - 2'), ('2020 - 1', '2020 - 1'), ('2020 - 2', '2020 - 2'), ('2021 - 1', '2021 - 1'), ('2021 - 2', '2021 - 2'), ('2022 - 1', '2022 - 1'), ('2022 - 2', '2022 - 2'), ('2023 - 1', '2023 - 1'), ('2023 - 2', '2023 - 2')], default=1)),
                ('column_a_general_text', models.CharField(max_length=50)),
                ('column_b_first_data', models.CharField(max_length=50)),
                ('column_c_second_data', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('indicator_url', models.CharField(max_length=200)),
                ('indicator_visible', models.BooleanField(default=True)),
                ('indicator_order', models.IntegerField(default=0)),
                ('status', models.IntegerField(choices=[(1, 'Activo'), (2, 'Inactivo'), (3, 'Eliminado')], default=1)),
                ('responsible', models.IntegerField(choices=[(1, 'Administrador')], default=1)),
                ('table_info', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.area')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalPractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('period', models.IntegerField(choices=[('2019 - 1', '2019 - 1'), ('2019 - 2', '2019 - 2'), ('2020 - 1', '2020 - 1'), ('2020 - 2', '2020 - 2'), ('2021 - 1', '2021 - 1'), ('2021 - 2', '2021 - 2'), ('2022 - 1', '2022 - 1'), ('2022 - 2', '2022 - 2'), ('2023 - 1', '2023 - 1'), ('2023 - 2', '2023 - 2')], null=True)),
                ('num_student_male', models.IntegerField(default=0)),
                ('num_student_female', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bachelor_program_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.bachelorprograminfo')),
            ],
        ),
        migrations.CreateModel(
            name='Pvvc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.IntegerField(choices=[('2019 - 1', '2019 - 1'), ('2019 - 2', '2019 - 2'), ('2020 - 1', '2020 - 1'), ('2020 - 2', '2020 - 2'), ('2021 - 1', '2021 - 1'), ('2021 - 2', '2021 - 2'), ('2022 - 1', '2022 - 1'), ('2022 - 2', '2022 - 2'), ('2023 - 1', '2023 - 1'), ('2023 - 2', '2023 - 2')], null=True)),
                ('num_students_male', models.IntegerField(default=0)),
                ('num_students_female', models.IntegerField(default=0)),
                ('qty_projects', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('BachelorProgramInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.bachelorprograminfo')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tags', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.area')),
                ('indicator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.indicator')),
            ],
        ),
        migrations.CreateModel(
            name='TagN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('idfc', models.CharField(max_length=512)),
                ('ca', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.area')),
                ('indicator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.indicator')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('status', models.IntegerField(choices=[(1, 'Activo'), (2, 'Inactivo'), (3, 'Eliminado')], default=1)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.area')),
            ],
        ),
        migrations.CreateModel(
            name='AccessArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.area')),
                ('indicatior_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.indicator')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.user')),
            ],
        ),
    ]
