# Generated by Django 5.0.6 on 2024-05-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvvc',
            name='name',
            field=models.CharField(default='PVVC', max_length=100),
        ),
    ]
