# Generated by Django 5.0.6 on 2024-05-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0003_alter_user_options_user_date_joined_user_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'JA'), (3, 'EG')], default=1),
        ),
    ]
