# Generated by Django 5.0.6 on 2024-05-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0004_remove_user_first_name_remove_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bachelorprograminfo',
            name='period',
            field=models.IntegerField(choices=[(20191, '2019 - 1'), (20192, '2019 - 2'), (20201, '2020 - 1'), (20202, '2020 - 2'), (20211, '2021 - 1'), (20212, '2021 - 2'), (20221, '2022 - 1'), (20222, '2022 - 2'), (20231, '2023 - 1'), (20232, '2023 - 2')], null=True),
        ),
        migrations.AlterField(
            model_name='indicator1',
            name='period',
            field=models.IntegerField(choices=[(20191, '2019 - 1'), (20192, '2019 - 2'), (20201, '2020 - 1'), (20202, '2020 - 2'), (20211, '2021 - 1'), (20212, '2021 - 2'), (20221, '2022 - 1'), (20222, '2022 - 2'), (20231, '2023 - 1'), (20232, '2023 - 2')], default=1),
        ),
        migrations.AlterField(
            model_name='professionalpractice',
            name='period',
            field=models.IntegerField(choices=[(20191, '2019 - 1'), (20192, '2019 - 2'), (20201, '2020 - 1'), (20202, '2020 - 2'), (20211, '2021 - 1'), (20212, '2021 - 2'), (20221, '2022 - 1'), (20222, '2022 - 2'), (20231, '2023 - 1'), (20232, '2023 - 2')], null=True),
        ),
        migrations.AlterField(
            model_name='pvvc',
            name='period',
            field=models.IntegerField(choices=[(20191, '2019 - 1'), (20192, '2019 - 2'), (20201, '2020 - 1'), (20202, '2020 - 2'), (20211, '2021 - 1'), (20212, '2021 - 2'), (20221, '2022 - 1'), (20222, '2022 - 2'), (20231, '2023 - 1'), (20232, '2023 - 2')], null=True),
        ),
    ]
